service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

plugins:
  - serverless-offline

functions:  
  todos:
    handler: src/api/todos.handler
    events: 
      - http: GET /api/todos
    
  todo:
    handler: src/api/todo.handler
    events: 
      - http: 
          path: /api/todos/{id}
          method: GET 
          request: 
            parameters:
              id: true

  
  api:
    handler: src/api/api.handler
    events: 
      - http: GET /api

  
    
